DGtal: DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector > Struct Template Reference
DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector > Struct Template Reference
Aim: Provides methods for building a stiffness and mass matrix to solve Poisson problems using the Finite Element Method using a corrected normal field.
#include <DGtal/dec/NormalCorrectedFEM.h>
Public Types
typedef TLinearAlgebraBackend LinearAlgebraBackend
typedef TRealPoint RealPoint
typedef TRealVector RealVector
typedef LinearAlgebraBackend::SparseMatrix LinearOperator
typedef LinearAlgebraBackend::DenseMatrix DenseMatrix
typedef LinearAlgebraBackend::DenseVector DenseVector
typedef SurfaceMesh< RealPoint, RealVector > Mesh
typedef Mesh::Vertex Vertex
typedef Mesh::Edge Edge
typedef Mesh::Face Face
typedef Mesh::Face Corner
typedef Mesh::Size Size
typedef LinearAlgebraBackend::Triplet Triplet
A triplet (row, col, value), useful for initializaing sparse matrices.
typedef std::vector< Triplet > Triplets
A range of triplets (row,col,value).
Public Member Functions
Initialization services
NormalCorrectedFEM ()
Default constructor. The object is invalid.
NormalCorrectedFEM (ConstAlias< Mesh > smesh, int order=1)
Standard services
DenseMatrix localL0 (Face f) const
LinearOperator L0 () const
LinearOperator M0 () const
LinearOperator lumpedM0 () const
Private Member Functions
void buildTriangleFaceMass (Triplets &triplets, Triplets &lumpedTriplets, Face f) const
void buildQuadrangleFaceMass (Triplets &triplets, Triplets &lumpedTriplets, Face f) const
DenseMatrix buildTriangleFaceStiffness (Face f) const
DenseMatrix buildQuadrangleFaceStiffness (Face f) const
LinearOperator buildMass ()
bool init (const Mesh *pMesh)
LinearOperator buildL0 () const
LinearOperator buildM0 () const
LinearOperator buildLumpedM0 () const
Private Attributes
const Mesh * myMesh
int order
Detailed Description
template<typename TLinearAlgebraBackend, typename TRealPoint, typename TRealVector>
struct DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >
Aim: Provides methods for building a stiffness and mass matrix to solve Poisson problems using the Finite Element Method using a corrected normal field.
Description of template class 'NormalCorrectedFEM'
Works with triangular and quadrangular surfaces.
Requires face normals on attached surface mesh.
Template Parameters
TLinearAlgebraBackend linear algebra backend used (i.e. EigenSparseLinearAlgebraBackend).
TRealPoint an arbitrary model of 3D RealPoint.
TRealVector an arbitrary model of 3D RealVector.
Definition at line 52 of file NormalCorrectedFEM.h.
Member Typedef Documentation
Corner
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef Mesh::Face DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Corner
Definition at line 64 of file NormalCorrectedFEM.h.
DenseMatrix
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef LinearAlgebraBackend::DenseMatrix DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::DenseMatrix
Definition at line 58 of file NormalCorrectedFEM.h.
DenseVector
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef LinearAlgebraBackend::DenseVector DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::DenseVector
Definition at line 59 of file NormalCorrectedFEM.h.
Edge
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef Mesh::Edge DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Edge
Definition at line 62 of file NormalCorrectedFEM.h.
Face
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef Mesh::Face DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Face
Definition at line 63 of file NormalCorrectedFEM.h.
LinearAlgebraBackend
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef TLinearAlgebraBackend DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::LinearAlgebraBackend
Definition at line 54 of file NormalCorrectedFEM.h.
LinearOperator
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef LinearAlgebraBackend::SparseMatrix DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::LinearOperator
Definition at line 57 of file NormalCorrectedFEM.h.
Mesh
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef SurfaceMesh<RealPoint, RealVector> DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Mesh
Definition at line 60 of file NormalCorrectedFEM.h.
RealPoint
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef TRealPoint DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::RealPoint
Definition at line 55 of file NormalCorrectedFEM.h.
RealVector
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef TRealVector DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::RealVector
Definition at line 56 of file NormalCorrectedFEM.h.
Size
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef Mesh::Size DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Size
Definition at line 65 of file NormalCorrectedFEM.h.
Triplet
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef LinearAlgebraBackend::Triplet DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Triplet
A triplet (row, col, value), useful for initializaing sparse matrices.
Definition at line 68 of file NormalCorrectedFEM.h.
Triplets
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef std::vector<Triplet> DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Triplets
A range of triplets (row,col,value).
Definition at line 70 of file NormalCorrectedFEM.h.
Vertex
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > typedef Mesh::Vertex DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::Vertex
Definition at line 61 of file NormalCorrectedFEM.h.
Constructor & Destructor Documentation
NormalCorrectedFEM() [1/2]
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::NormalCorrectedFEM () inline
Default constructor. The object is invalid.
Definition at line 379 of file NormalCorrectedFEM.h.
                         : myMesh( nullptr )
    {
    }
NormalCorrectedFEM() [2/2]
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::NormalCorrectedFEM (ConstAlias< Mesh > smesh, int order = 1) inline
Constructor from surface mesh smesh.
Parameters
smesh any surface mesh
Definition at line 385 of file NormalCorrectedFEM.h.
      : myMesh( nullptr ), order( order )
    {
      init( &smesh );
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::init().
Member Function Documentation
buildL0()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > LinearOperator DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildL0 () const inline private
Definition at line 292 of file NormalCorrectedFEM.h.
    {
      LinearOperator L( myMesh->nbVertices(), myMesh->nbVertices() );
      Triplets triplets;
      DenseMatrix values;
      for ( Face f = 0; f < myMesh->nbFaces(); f++ )
      {
        const auto vtcs = myMesh->incidentVertices( f );
        if ( vtcs.size() == 3 )
          values = buildTriangleFaceStiffness( f );
        else if ( vtcs.size() == 4 )
          values = buildQuadrangleFaceStiffness( f );
        else
        {
          trace.error() << "[NormalCorrectedFEM::init]"
                        << " faces should be triangle or quadrangles"
                        << std::endl;
          return L;
        }
        for ( int i = 0; i < values.rows(); i++ )
          for ( int j = 0; j < values.cols(); j++ )
            triplets.push_back( { vtcs[ i ], vtcs[ j ], values( i, j ) } );
      }
      L.setFromTriplets( triplets.cbegin(), triplets.cend() );
      return -L;
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceStiffness(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceStiffness(), DGtal::Trace::error(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbFaces(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbVertices(), and DGtal::trace.
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::L0().
buildLumpedM0()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > LinearOperator DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildLumpedM0 () const inline private
Definition at line 345 of file NormalCorrectedFEM.h.
    {
      LinearOperator lumpedM( myMesh->nbVertices(), myMesh->nbVertices() );
      Triplets triplets;
      Triplets lumpedTriplets;
      for ( Face f = 0; f < myMesh->nbFaces(); f++ )
      {
        const auto vtcs = myMesh->incidentVertices( f );
        if ( vtcs.size() == 3 )
          buildTriangleFaceMass( triplets, lumpedTriplets, f );
        else if ( vtcs.size() == 4 )
          buildQuadrangleFaceMass( triplets, lumpedTriplets, f );
        else
        {
          trace.error() << "[NormalCorrectedFEM::buildLumpedM0]"
                        << " faces should be triangles or quadrangles"
                        << std::endl;
          return lumpedM;
        }
      }
      lumpedM.setFromTriplets( lumpedTriplets.cbegin(), lumpedTriplets.cend() );
      return lumpedM;
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceMass(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceMass(), DGtal::Trace::error(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbFaces(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbVertices(), and DGtal::trace.
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::lumpedM0().
buildM0()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > LinearOperator DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildM0 () const inline private
Definition at line 320 of file NormalCorrectedFEM.h.
    {
      LinearOperator M( myMesh->nbVertices(), myMesh->nbVertices() );
      Triplets triplets;
      Triplets lumpedTriplets;
      for ( Face f = 0; f < myMesh->nbFaces(); f++ )
      {
        const auto vtcs = myMesh->incidentVertices( f );
        if ( vtcs.size() == 3 )
          buildTriangleFaceMass( triplets, lumpedTriplets, f );
        else if ( vtcs.size() == 4 )
          buildQuadrangleFaceMass( triplets, lumpedTriplets, f );
        else
        {
          trace.error() << "[NormalCorrectedFEM::buildM0]"
                        << " faces should be triangles or quadrangles"
                        << std::endl;
          return M;
        }
      }
      M.setFromTriplets( triplets.cbegin(), triplets.cend() );
      return M;
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceMass(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceMass(), DGtal::Trace::error(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbFaces(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbVertices(), and DGtal::trace.
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::M0().
buildMass()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > LinearOperator DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildMass () inline private
Definition at line 269 of file NormalCorrectedFEM.h.
    {
      return true;
    }
buildQuadrangleFaceMass()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > void DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceMass (Triplets & triplets, Triplets & lumpedTriplets, Face f) const inline private
Definition at line 104 of file NormalCorrectedFEM.h.
    {
      const auto vtcs   = myMesh->incidentVertices( f );
      const auto v0     = vtcs[ 0 ];
      const auto v1     = vtcs[ 1 ];
      const auto v2     = vtcs[ 2 ];
      const auto v3     = vtcs[ 3 ];
      const auto xij    = myMesh->position( v1 ) - myMesh->position( v0 );
      const auto xil    = myMesh->position( v3 ) - myMesh->position( v0 );
      const auto nn     = xij.crossProduct( xil ).getNormalized();
      const auto face_n = myMesh->faceNormal( f );
      const double z    = nn.dot( face_n );
      if ( z < 0. )
      {
        trace.warning() << "Bad corrected normals at face " << f << std::endl;
      }
      double area     = xij.crossProduct( xil ).norm();
      int v[ 2 ][ 2 ] = { { (int)v0, (int)v1 }, { (int)v3, (int)v2 } };
      for ( int i = 0; i < 2; i++ )
      {
        for ( int j = 0; j < 2; j++ )
        {
          for ( int i2 = 0; i2 < 2; i2++ )
          {
            for ( int j2 = 0; j2 < 2; j2++ )
            {
              int v_i = v[ i ][ j ];
              int v_j = v[ i2 ][ j2 ];
              if ( i == i2 && j == j2 )
              {
                triplets.push_back( { v_i, v_j, area * z * 1. / 9. } );
                lumpedTriplets.push_back( { v_i, v_j, 1. / 4. * z * area } );
              }
              else if ( i == i2 && j == 1 - j2 )
              {
                triplets.push_back( { v_i, v_j, area * z * 1. / 18. } );
              }
              else if ( j == j2 && i == 1 - i2 )
              {
                triplets.push_back( { v_i, v_j, area * z * 1. / 18. } );
              }
              else
              {
                triplets.push_back( { v_i, v_j, area * z * 1. / 36. } );
              }
            }
          }
        }
      }
    }
References DGtal::SurfaceMesh< TRealPoint, TRealVector >::faceNormal(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, DGtal::SurfaceMesh< TRealPoint, TRealVector >::position(), DGtal::trace, and DGtal::Trace::warning().
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildLumpedM0(), and DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildM0().
buildQuadrangleFaceStiffness()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > DenseMatrix DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceStiffness (Face f) const inline private
Definition at line 221 of file NormalCorrectedFEM.h.
    {
      DenseMatrix res   = DenseMatrix( 4, 4 );
      const auto vtcs   = myMesh->incidentVertices( f );
      const auto v0     = vtcs[ 0 ];
      const auto v1     = vtcs[ 1 ];
      const auto v2     = vtcs[ 2 ];
      const auto v3     = vtcs[ 3 ];
      const auto xij    = myMesh->position( v1 ) - myMesh->position( v0 );
      const auto xil    = myMesh->position( v3 ) - myMesh->position( v0 );
      const auto nn     = xij.crossProduct( xil ).getNormalized();
      const auto face_n = myMesh->faceNormal( f );
      const double x    = face_n.dot( xij.getNormalized() );
      const double y    = face_n.dot( xil.getNormalized() );
      const double z    = face_n.dot( nn );
      if ( z < 0. )
      {
        trace.warning() << "Bad corrected normals at face " << f << std::endl;
      }
      const double lap  = 0.5 * ( x * y / z );
      const double sqx  = 1. - x * x;
      const double sqy  = 1. - y * y;
      const double self = lap + 1. / 3. * ( sqx + sqy ) / z;
      const double op1  = -1. / 3. * sqy / z + 1. / 6. * sqx / z;
      const double op2  = -1. / 3. * sqx / z + 1. / 6. * sqy / z;
      const double op   = -lap - 1. / 6. * ( sqx + sqy ) / z;
      res( 0, 0 )       = self;
      res( 0, 1 )       = op1;
      res( 0, 2 )       = op;
      res( 0, 3 )       = op2;
      res( 1, 0 ) = op1;
      res( 1, 1 ) = self - 2. * lap;
      res( 1, 2 ) = op2;
      res( 1, 3 ) = op + 2. * lap;
      res( 2, 0 ) = op;
      res( 2, 1 ) = op2;
      res( 2, 2 ) = self;
      res( 2, 3 ) = op1;
      res( 3, 0 ) = op2;
      res( 3, 1 ) = op + 2. * lap;
      res( 3, 2 ) = op1;
      res( 3, 3 ) = self - 2. * lap;
      return res;
    }
References DGtal::SurfaceMesh< TRealPoint, TRealVector >::faceNormal(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, DGtal::SurfaceMesh< TRealPoint, TRealVector >::position(), DGtal::trace, and DGtal::Trace::warning().
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildL0(), and DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::localL0().
buildTriangleFaceMass()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > void DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceMass (Triplets & triplets, Triplets & lumpedTriplets, Face f) const inline private
Definition at line 76 of file NormalCorrectedFEM.h.
    {
      const auto vtcs         = myMesh->incidentVertices( f );
      const auto v0           = vtcs[ 0 ];
      const auto v1           = vtcs[ 1 ];
      const auto v2           = vtcs[ 2 ];
      const auto xij          = myMesh->position( v1 ) - myMesh->position( v0 );
      const auto xik          = myMesh->position( v2 ) - myMesh->position( v0 );
      const auto n            = xij.crossProduct( xik );
      const auto nn           = n.getNormalized();
      const auto face_n       = myMesh->faceNormal( f );
      const double z          = face_n.dot( nn );
      const double doubleArea = n.norm();
      triplets.push_back( { v0, v0, 1. / 12. * z * doubleArea } );
      triplets.push_back( { v0, v1, 1. / 24. * z * doubleArea } );
      triplets.push_back( { v0, v2, 1. / 24. * z * doubleArea } );
      triplets.push_back( { v1, v0, 1. / 24. * z * doubleArea } );
      triplets.push_back( { v1, v1, 1. / 12. * z * doubleArea } );
      triplets.push_back( { v1, v2, 1. / 24. * z * doubleArea } );
      triplets.push_back( { v2, v0, 1. / 24. * z * doubleArea } );
      triplets.push_back( { v2, v1, 1. / 24. * z * doubleArea } );
      triplets.push_back( { v2, v2, 1. / 12. * z * doubleArea } );
      lumpedTriplets.push_back( { v0, v0, 1. / 6. * z * doubleArea } );
      lumpedTriplets.push_back( { v1, v1, 1. / 6. * z * doubleArea } );
      lumpedTriplets.push_back( { v2, v2, 1. / 6. * z * doubleArea } );
    }
References DGtal::SurfaceMesh< TRealPoint, TRealVector >::faceNormal(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, and DGtal::SurfaceMesh< TRealPoint, TRealVector >::position().
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildLumpedM0(), and DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildM0().
buildTriangleFaceStiffness()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > DenseMatrix DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceStiffness (Face f) const inline private
Definition at line 157 of file NormalCorrectedFEM.h.
    {
      DenseMatrix res     = DenseMatrix( 3, 3 );
      const auto vtcs     = myMesh->incidentVertices( f );
      const auto v0       = vtcs[ 0 ];
      const auto v1       = vtcs[ 1 ];
      const auto v2       = vtcs[ 2 ];
      const auto xij      = myMesh->position( v1 ) - myMesh->position( v0 );
      const auto xik      = myMesh->position( v2 ) - myMesh->position( v0 );
      const auto n        = xij.crossProduct( xik );
      const auto nn       = n.getNormalized();
      const auto xil      = nn.crossProduct( xij ).getNormalized();
      const auto face_n   = myMesh->faceNormal( f );
      const double x      = face_n.dot( xij.getNormalized() );
      const double y      = face_n.dot( xil );
      const double z      = face_n.dot( nn );
      const double l1     = xij.norm();
      const double l2     = xik.norm();
      const double cos_t  = xij.dot( xik ) / ( l1 * l2 );
      const double sin_t  = n.norm() / ( l1 * l2 );
      const double x2     = x * x;
      const double y2     = y * y;
      const double z2     = z * z;
      const double l12    = l1 * l1;
      const double l22    = l2 * l2;
      const double cos_t2 = cos_t * cos_t;
      const double sin_t2 = sin_t * sin_t;
      res( 0, 0 ) =
      1. / 2 *
      ( 2 * ( l1 * l2 - cos_t * l22 ) * sin_t * x * y - 2 * cos_t * l1 * l2 +
        l22 * sin_t2 * z2 - l22 * sin_t2 +
        ( 2 * cos_t * l1 * l2 + 2 * l22 * sin_t2 - l12 - l22 ) * x2 + l12 +
        l22 ) /
      ( l1 * l2 * sin_t * z );
      res( 1, 0 ) =
      1. / 2 *
      ( ( 2 * cos_t * l2 - l1 ) * sin_t * x * y + l2 * sin_t2 * y2 +
        cos_t * l1 - ( cos_t * l1 + l2 * sin_t2 - l2 ) * x2 - l2 ) /
      ( l1 * sin_t * z );
      res( 2, 0 ) =
      -1. / 2 *
      ( l2 * sin_t * x * y - cos_t * l2 + ( cos_t * l2 - l1 ) * x2 + l1 ) /
      ( l2 * sin_t * z );
      res( 0, 1 ) =
      1. / 2 *
      ( ( 2 * cos_t * l2 - l1 ) * sin_t * x * y + l2 * sin_t2 * y2 +
        cos_t * l1 - ( cos_t * l1 + l2 * sin_t2 - l2 ) * x2 - l2 ) /
      ( l1 * sin_t * z );
      res( 1, 1 ) = -1. / 2 *
                    ( 2 * cos_t * l2 * sin_t * x * y + cos_t2 * l2 * x2 -
                      ( cos_t2 - 1 ) * l2 * y2 - l2 ) /
                    ( l1 * sin_t * z );
      res( 2, 1 ) =
      1. / 2 * ( sin_t * x * y + cos_t * x2 - cos_t ) / ( sin_t * z );
      res( 0, 2 ) =
      -1. / 2 *
      ( l2 * sin_t * x * y - cos_t * l2 + ( cos_t * l2 - l1 ) * x2 + l1 ) /
      ( l2 * sin_t * z );
      res( 1, 2 ) =
      1. / 2 * ( sin_t * x * y + cos_t * x2 - cos_t ) / ( sin_t * z );
      res( 2, 2 ) = -1. / 2 * ( l1 * x2 - l1 ) / ( l2 * sin_t * z );
      return res;
    }
References DGtal::SurfaceMesh< TRealPoint, TRealVector >::faceNormal(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, and DGtal::SurfaceMesh< TRealPoint, TRealVector >::position().
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildL0(), and DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::localL0().
init()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > bool DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::init (const Mesh * pMesh) inline private
Definition at line 274 of file NormalCorrectedFEM.h.
    {
      myMesh = pMesh;
      if ( order != 1 )
      {
        trace.error() << "[NormalCorrectedFEM::init]"
                      << " order should be 1" << std::endl;
        return false;
      }
      if ( myMesh->faceNormals().empty() )
      {
        trace.error() << "[NormalCorrectedFEM::init]"
                      << " face normals should be provided." << std::endl;
        return false;
      }
      return true;
    }
References DGtal::Trace::error(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::faceNormals(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, and DGtal::trace.
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::NormalCorrectedFEM().
L0()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > LinearOperator DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::L0 () const inline
Return the global stiffness matrix n_v x n_v.
Returns
the n_v x n_v stiffness matrix
Note
The sign convention for the divergence and the Laplacian operator is opposite to the one of [44] . This is to match the usual mathematical convention that the Laplacian (and the Laplacian-Beltrami) has negative eigenvalues (and is the sum of second derivatives in the cartesian grid). It also follows the formal adjointness of exterior derivative and opposite of divergence as relation \(\langle \mathrm{d} u, v \rangle = - \langle u, \mathrm{div} v \rangle \). See also https://en.wikipedia.org/wiki/LaplaceBeltrami_operator
Definition at line 427 of file NormalCorrectedFEM.h.
    {
      return buildL0();
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildL0().
localL0()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > DenseMatrix DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::localL0 (Face f) const inline
Return the stiffness matrix degree x degree of the face.
Parameters
f a face
Returns
the degree x degree stiffness matrix
Definition at line 398 of file NormalCorrectedFEM.h.
    {
      const auto vtcs = myMesh->incidentVertices( f );
      if ( vtcs.size() == 3 )
        return -buildTriangleFaceStiffness( f );
      else if ( vtcs.size() == 4 )
        return -buildQuadrangleFaceStiffness( f );
      else
      {
        trace.error() << "[NormalCorrectedFEM::buildLocalL0]"
                      << " faces should be triangles or quadrangles"
                      << std::endl;
        return DenseMatrix();
      }
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceStiffness(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceStiffness(), DGtal::Trace::error(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::incidentVertices(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh, and DGtal::trace.
lumpedM0()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > LinearOperator DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::lumpedM0 () const inline
Return the global lumped mass matrix n_v x n_v. This matrix is diagonal. To obtain a (more precise) non diagonal version use M0()
Returns
the n_v x n_v mass matrix
Definition at line 445 of file NormalCorrectedFEM.h.
    {
      return buildLumpedM0();
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildLumpedM0().
M0()
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > LinearOperator DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::M0 () const inline
Return the global mass matrix n_v x n_v. This matrix is not diagonal. To obtain a (less precise) diagonal version use lumpedM0()
Returns
the n_v x n_v mass matrix
Definition at line 436 of file NormalCorrectedFEM.h.
    {
      return buildM0();
    }
References DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildM0().
Field Documentation
myMesh
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > const Mesh* DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::myMesh private
Definition at line 371 of file NormalCorrectedFEM.h.
Referenced by DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildL0(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildLumpedM0(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildM0(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceMass(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildQuadrangleFaceStiffness(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceMass(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::buildTriangleFaceStiffness(), DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::init(), and DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::localL0().
order
template<typename TLinearAlgebraBackend , typename TRealPoint , typename TRealVector > int DGtal::NormalCorrectedFEM< TLinearAlgebraBackend, TRealPoint, TRealVector >::order private
Definition at line 372 of file NormalCorrectedFEM.h.
The documentation for this struct was generated from the following file:
NormalCorrectedFEM.h